project:
  type: book

book:
  title: "Setting up my working environment"
  author: "Philippe Massicotte"
  chapters:
    - index.qmd
    - terminal.qmd
    - neovim.qmd
    - installr.qmd
    - gis.qmd
    - nemo.qmd
    - misc.qmd

format:
  html:
    page-layout: full
    toc: true
    toc-location: right
    
execute:
  freeze: true  # never re-render during project render