# Terminal

Setting up my terminal environment. The dimensions of my terminal is 150 columns by 35 rows.

## kitty terminal emulator

I am using [kitty](https://sw.kovidgoyal.net/kitty/) as my terminal emulator. See the [dotfiles](dotfiles.qmd)

### Installation

- https://www.linuxfordevices.com/tutorials/ubuntu/install-kitty

Do not forget to recreate the symbolic link to the kitty binary after an update.

### Kitty themes

- https://github.com/kovidgoyal/kitty-themes

Type:

```bash
kitty +kitten themes
```

### Remote ssh

```bash
kitty +kitten ssh filoche@beluga.computecanada.ca
edit-in-kitt filename
```
- https://sw.kovidgoyal.net/kitty/kittens/remote_file/
- https://sw.kovidgoyal.net/kitty/shell-integration/#shell-integration-over-ssh

## Fonts

### JetBrains font

For my daily to go programming font.

```bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/install_manual.sh)"
```
### Meslo Nerd font (for Powerlevl10k)

Got on [this page](https://github.com/romkatv/powerlevel10k/blob/master/font.md) and download and install the `.ttf` files.

## zsh

```bash
sudo apt install zsh
```

### oh-my-zsh

[Install oh-my-zsh](https://ohmyz.sh/#install)

```bash
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
```

### power10k theme

[Powerlevel10k theme](https://github.com/romkatv/powerlevel10k)

```bash
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
```
Then, set `ZSH_THEME="powerlevel10k/powerlevel10k"` in `~/.zshrc` and configure the theme as follow:

```bash
p10k configure
```

## Useful tools

- [Useful tools written in rust](https://zaiste.net/posts/shell-commands-rust/)

For some of these tools, rust needs to be [installed](https://www.rust-lang.org/tools/install).

```bash
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

To update installed cargo packages:

```bash
cargo install cargo-update
cargo install-update -l
cargo install-update -a
```

### tldr

```bash
sudo apt install tldr
tldr --update
```

### exa

```bash
cargo install exa 
```

### bat

```bash
cargo install bat 
```

### Creating alias

```bash
nano ~/.zshrc 
```

Add these alias to the file.

```bash
alias ls='exa --icons'
alias l='exa'
alias la='exa -a'
alias ll='exa -lahF --icons'
alias cat=bat
```

### fzf

[fzf](https://github.com/junegunn/fzf) is a command-line fuzzy finder.

```bash
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install
```

Then, set `plugins=(fzf)` in `~/.zshrc`.

### The Silver Searcher

[The Silver Searcher](https://github.com/ggreer/the_silver_searcher)

```bash
sudo apt-get install silversearcher-ag
```

### ripgrep

https://github.com/BurntSushi/ripgrep

Easier to use to me.

```bash
rg read.csv -g "*.R"
```
### gdu - go DiskUsage()

Pretty fast disk usage analyzer written in Go: https://github.com/dundee/gdu

```bash
add-apt-repository ppa:daniel-milde/gdu
apt-get update
apt-get install gdu
```

### nala

> Nala is a front-end for `libapt-pkg`. Specifically we interface using the `python-apt` api.

- [Installation](https://github.com/volitank/nala)

### btop

- https://github.com/aristocratos/btop

### Broot

- https://github.com/Canop/broot

```bash
cargo install --locked broot
```

