# Visual Studio Code

## Using VScode for R development

On Linux Mint, the default R installation directory is not the same as on Ubuntu. I have configured VScode to use the R bin installation directory of Ubuntu. Hence, on Mint, code completion, help viewer are not working. The simple work around is to create a symbolic link?

```bash
sudo ln -s /usr/bin/R /usr/local/bin/R
```

## Show plot externally on a web browser

Use this in `.Rprofile` **inside** a project directory or globally.

```r
if (interactive() && Sys.getenv("RSTUDIO") == "") {
  Sys.setenv(TERM_PROGRAM = "vscode")
  if ("httpgd" %in% .packages(all.available = TRUE)) {
    options(vsc.plot = FALSE)
    options(device = function(...) {
      httpgd::hgd(silent = TRUE)
      .vsc.browser(httpgd::hgd_url(history = FALSE), viewer = FALSE)
    })
  }
}


# Use an external browser for displaying html files, such as {gt} and {xaringan}
options(vsc.viewer = FALSE)
# External browser for web apps, such as {shiny}
options(vsc.browser = FALSE)
# View help page in an external browser
options(vsc.helpPanel = FALSE)
# Use original data viewer
options(vsc.view = FALSE)
```

If you close the web page by accident, it can be reopened using `ctrl+alt+p` (depending on the chosen keybinding).

```json
{
  "key": "ctrl+alt+p",
  "command": "r.runCommand",
  "when": "editorTextFocus && editorLangId == 'r'",
  "args": ".vsc.browser(httpgd::hgd_url(), viewer = FALSE)"
},
```

::: {.callout-important}
Do not forget to install the `httpdg` package. Otherwise, plot will be displayed as png in an external window.
:::

## Debugging

Debugging can be done using the [VSCode-R-Debugger package](https://github.com/ManuelHentschel/VSCode-R-Debugger).

```r
remotes::install_github("ManuelHentschel/vscDebugger")
```

This `.vscode/launch.json` configuration file is placed in the project root directory:

```json
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "R-Debugger",
      "request": "attach",
      "name": "Attach to R process"
    }
  ]
}
```

Open the R terminal and type:

```r
vscDebugger::.vsc.listenForDAP()
```

Then, press `F5`to start the debugger. 
